#!/usr/bin/env bash
# Transfer a file from client to server
if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$4" -o stricthostkeychecking=no "$1" "$3@$2":~/
fi
