#!/usr/bin/env bash
# Write a bash script that displays
# 'To infinity and beyond' indefinitely.
# 'I am invincible!!!' when receiving a SIGTERM signal.
trap "echo I am invincible!!!" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
