#!/usr/bin/env bash
# This script displays certain categories in the /etc/passwd file.
# Colon separated username, group id, and shell full path for user.
while read line
do
    echo "$line" | cut -d':' -f1,3,6
done </etc/passwd
