#!/usr/bin/env bash
# This script parses /etc/passwd file to tell a story..
while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do
    echo -n "The user $f1 is part of the $f4 gang, lives in $f6 and rides $f7. "
    echo -n "$f3's place is protected by the passcode $f2, more info about the "
    echo "user here: $f5"
done < /etc/passwd
