#!/usr/bin/env bash
# Configure an Ubuntu server so localhost resolves to 127.0.0.2
# and facebook.com resolves to 8.8.8.8
file=/etc/hosts

sudo sed -i -e '$a\\n127.0.0.2\t127.0.0.1' $file
sudo sed -i -e '$a\\n8.8.8.8\tfacebook.com\n' $file
