#!/usr/bin/env bash
# This script displays "bad luck" on 4th loop.
# "good luck" on 8th loop
# "Holberton School" on every other line up to 10 lines
COUNTER=1
while [ $COUNTER -le 10 ]; do
      if [ $COUNTER -eq 4 ]
      then
	echo bad luck
      elif [ $COUNTER -eq 8 ]
      then
	echo good luck
      else
	echo Holberton School
      fi
      let COUNTER+=1
done
