#!/usr/bin/env bash
# This script displays "Holberton School" 10 times
COUNTER=1
while [ $COUNTER -le 10 ]; do
      if [ $COUNTER -eq 4 ]
      then
	echo bad luck
      elif [ $COUNTER -eq 8 ]
      then
	echo good luck
      else
	echo Holberton School
      fi
      let COUNTER+=1
done
